hardware_interface:
  sim_control_mode: 0
  joints: &joints
  - left_arm_0_joint
  - left_arm_1_joint
  - left_arm_2_joint
  - left_arm_3_joint
  - left_arm_4_joint
  - left_arm_5_joint
  - left_arm_6_joint
  - right_arm_0_joint
  - right_arm_1_joint
  - right_arm_2_joint
  - right_arm_3_joint
  - right_arm_4_joint
  - right_arm_5_joint
  - right_arm_6_joint
  - triangle_base_joint
  - neck_shoulder_pan_joint
  - neck_shoulder_lift_joint
  - neck_elbow_joint
  - neck_wrist_1_joint
  - neck_wrist_2_joint
  - neck_wrist_3_joint
  - left_gripper_joint
  - right_gripper_joint
  - odom_x_joint
  - odom_y_joint
  - odom_z_joint
generic_hw_control_loop:
  loop_hz: &loop_rate 100
  cycle_time_error_threshold: 0.015
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: *loop_rate
whole_body_controller_l_arm: &whole_body_controller_l_arm
  type: position_controllers/JointTrajectoryController  
  joints:
  - left_arm_0_joint
  - left_arm_1_joint
  - left_arm_2_joint
  - left_arm_3_joint
  - left_arm_4_joint
  - left_arm_5_joint
  - left_arm_6_joint
whole_body_controller/left_arm: *whole_body_controller_l_arm
whole_body_controller_r_arm: &whole_body_controller_r_arm
  type: position_controllers/JointTrajectoryController  
  joints:
  - right_arm_0_joint
  - right_arm_1_joint
  - right_arm_2_joint
  - right_arm_3_joint
  - right_arm_4_joint
  - right_arm_5_joint
  - right_arm_6_joint
whole_body_controller/right_arm: *whole_body_controller_r_arm
whole_body_controller_torso: &whole_body_controller_torso
  type: position_controllers/JointTrajectoryController  
  joints:
    - triangle_base_joint
whole_body_controller/torso: *whole_body_controller_torso
whole_body_controller_neck: &whole_body_controller_neck
  type: position_controllers/JointTrajectoryController  
  joints:
  - neck_shoulder_pan_joint
  - neck_shoulder_lift_joint
  - neck_elbow_joint
  - neck_wrist_1_joint
  - neck_wrist_2_joint
  - neck_wrist_3_joint
whole_body_controller/neck: *whole_body_controller_neck
whole_body_controller_r_gripper: &whole_body_controller_r_gripper
  type: position_controllers/JointTrajectoryController  
  joints:
    - right_gripper_joint
whole_body_controller/right_gripper: *whole_body_controller_r_gripper
whole_body_controller_l_gripper: &whole_body_controller_l_gripper
  type: position_controllers/JointTrajectoryController  
  joints:
    - left_gripper_joint
whole_body_controller/left_gripper: *whole_body_controller_l_gripper
joint_group_pos_controller:
   type: position_controllers/JointGroupPositionController
   joints: *joints