#!/bin/bash

rostopic pub /boxy/commands sensor_msgs/JointState "header:
  seq: 0
  stamp: {secs: 0, nsecs: 0}
  frame_id: ''
name: ['odom_x_joint', 'odom_z_joint']
position: [0, 0]
velocity: [0.2, 0.1]
effort: [0]" -r 100
