#!/bin/bash

rosservice call /boxy/set_joint_states "state:
  header:
    seq: 0
    stamp: {secs: 0, nsecs: 0}
    frame_id: ''
  name: ['odom_x_joint', 'odom_z_joint', 'right_arm_4_joint', 'left_arm_0_joint', 'left_arm_1_joint']
  position: [0.1, 0.3, -1.3, -1.56, 0.84]
  velocity: [0, 0, 0, 0, 0]
  effort: [0]"
